<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>1.0.0.0</Version>
        <DebugType>portable</DebugType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup>
        <Author>Zeffuro</Author>
        <Name>LiteShade</Name>
        <InternalName>LiteShade</InternalName>
        <Punchline>A little less green.</Punchline>
        <Description>Tweak the game's colours, use GPose filters anywhere, and add optional depth of field or vignette.</Description>
        <RepoUrl>https://github.com/Zeffuro/LiteShade</RepoUrl>
        <IconUrl>https://raw.githubusercontent.com/Zeffuro/LiteShade/master/Images/icon.png</IconUrl>
        <ImageUrls></ImageUrls>
        <Tags>graphics;colour;color;filters;shaders;presets;gpose;dof;vignette;qol</Tags>
        <AcceptsFeedback>true</AcceptsFeedback>
    </PropertyGroup>
    <ItemGroup>
      <Content Include="changelog.md" />
    </ItemGroup>
</Project>
